### ISSUE TITLE
make test fails; dependency versions too loose?

### ISSUE THREAD

**Issue by roman-neuhauser** [jgonera/webspecter#11]
git clone:

```
roman@wrench ~/wc/MINE 0 1078 0 > git clone --recursive https://github.com/jgonera/webspecter.git webspecter-upstream
Cloning into 'webspecter-upstream'...
remote: Reusing existing pack: 608, done.
remote: Total 608 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (608/608), 179.91 KiB | 187.00 KiB/s, done.
Resolving deltas: 100% (319/319), done.
Checking connectivity... done.
Submodule 'node_modules/chai' (https://github.com/chaijs/chai.git) registered for path 'node_modules/chai'
Submodule 'node_modules/commander' (https://github.com/visionmedia/commander.js.git) registered for path 'node_modules/commander'
Submodule 'node_modules/debug' (https://github.com/visionmedia/debug.git) registered for path 'node_modules/debug'
Submodule 'node_modules/diff' (https://github.com/kpdecker/jsdiff.git) registered for path 'node_modules/diff'
Submodule 'node_modules/mocha' (https://github.com/visionmedia/mocha.git) registered for path 'node_modules/mocha'
Submodule 'nodify' (https://github.com/jgonera/phantomjs-nodify.git) registered for path 'nodify'
Cloning into 'node_modules/chai'...
remote: Reusing existing pack: 4295, done.
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 4329 (delta 21), reused 21 (delta 10)
Receiving objects: 100% (4329/4329), 1.77 MiB | 278.00 KiB/s, done.
Resolving deltas: 100% (1939/1939), done.
Checking connectivity... done.
Submodule path 'node_modules/chai': checked out 'ca5368cf65fb50a3e19403195d4465657a241202'
Cloning into 'node_modules/commander'...
remote: Reusing existing pack: 1012, done.
remote: Total 1012 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1012/1012), 184.77 KiB | 146.00 KiB/s, done.
Resolving deltas: 100% (509/509), done.
Checking connectivity... done.
Submodule path 'node_modules/commander': checked out '77a337fffb69eb53ec2cc0cb1b23cfd7270f7f71'
Cloning into 'node_modules/debug'...
remote: Reusing existing pack: 430, done.
remote: Total 430 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (430/430), 61.07 KiB | 80.00 KiB/s, done.
Resolving deltas: 100% (213/213), done.
Checking connectivity... done.
Submodule path 'node_modules/debug': checked out '497a088b5f7a48a0c2ef10c8bd5aaf06e0f9d129'
Cloning into 'node_modules/diff'...
remote: Reusing existing pack: 263, done.
remote: Total 263 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (263/263), 68.17 KiB | 67.00 KiB/s, done.
Resolving deltas: 100% (132/132), done.
Checking connectivity... done.
Submodule path 'node_modules/diff': checked out '205547ab0093ff2afb1f7d8e9311a41993a55e5d'
Cloning into 'node_modules/mocha'...
remote: Reusing existing pack: 7168, done.
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 7176 (delta 2), reused 2 (delta 0)
Receiving objects: 100% (7176/7176), 4.03 MiB | 175.00 KiB/s, done.
Resolving deltas: 100% (3697/3697), done.
Checking connectivity... done.
Submodule path 'node_modules/mocha': checked out '6b0a61266ef42edba11b2d5da0defc5cd5d30eb4'
Cloning into 'nodify'...
remote: Reusing existing pack: 199, done.
remote: Total 199 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (199/199), 121.41 KiB | 67.00 KiB/s, done.
Resolving deltas: 100% (92/92), done.
Checking connectivity... done.
Submodule path 'nodify': checked out 'b812c24869527b054a77b1ff0cca47390e7060fb'
Submodule 'support/node_modules/chai' (https://github.com/chaijs/chai.git) registered for path 'support/node_modules/chai'
Submodule 'support/node_modules/debug' (https://github.com/visionmedia/debug.git) registered for path 'support/node_modules/debug'
Submodule 'support/node_modules/diff' (https://github.com/kpdecker/jsdiff.git) registered for path 'support/node_modules/diff'
Submodule 'support/node_modules/mocha' (https://github.com/visionmedia/mocha.git) registered for path 'support/node_modules/mocha'
Cloning into 'support/node_modules/chai'...
remote: Reusing existing pack: 4295, done.
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 4329 (delta 21), reused 21 (delta 10)
Receiving objects: 100% (4329/4329), 1.77 MiB | 393.00 KiB/s, done.
Resolving deltas: 100% (1939/1939), done.
Checking connectivity... done.
Submodule path 'nodify/support/node_modules/chai': checked out '0191e762b9e5f12acd6df748c5a30736de8dfe82'
Cloning into 'support/node_modules/debug'...
remote: Reusing existing pack: 430, done.
remote: Total 430 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (430/430), 61.07 KiB | 34.00 KiB/s, done.
Resolving deltas: 100% (213/213), done.
Checking connectivity... done.
Submodule path 'nodify/support/node_modules/debug': checked out 'a0b3cceb19a525b992d843ae61090e96ed598b1f'
Cloning into 'support/node_modules/diff'...
remote: Reusing existing pack: 263, done.
remote: Total 263 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (263/263), 68.17 KiB | 0 bytes/s, done.
Resolving deltas: 100% (132/132), done.
Checking connectivity... done.
Submodule path 'nodify/support/node_modules/diff': checked out '5b5b6ac22c4a6fa4a02a50c384633714207d2d27'
Cloning into 'support/node_modules/mocha'...
remote: Reusing existing pack: 7168, done.
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 7176 (delta 2), reused 2 (delta 0)
Receiving objects: 100% (7176/7176), 4.03 MiB | 235.00 KiB/s, done.
Resolving deltas: 100% (3697/3697), done.
Checking connectivity... done.
Submodule path 'nodify/support/node_modules/mocha': checked out '98aad6efdb195df715d88ed2f5633616bbf2ed12'
roman@wrench ~/wc/MINE 0 1079 0 > 
```

npm ls:

```
roman@wrench wc/MINE/webspecter-upstream master 0 1082 2 > npm ls
npm WARN unmet dependency /home/roman/wc/MINE/webspecter-upstream/node_modules/mocha requires commander@'0.5.x' but will load
npm WARN unmet dependency /home/roman/wc/MINE/webspecter-upstream/node_modules/commander,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /home/roman/wc/MINE/webspecter-upstream/node_modules/mocha requires diff@'1.0.2' but will load
npm WARN unmet dependency /home/roman/wc/MINE/webspecter-upstream/node_modules/diff,
npm WARN unmet dependency which is version 1.0.3
/home/roman/wc/MINE/webspecter-upstream
├── chai@1.0.1
├── commander@1.0.1 invalid
├── debug@0.1.0
├── diff@1.0.3 invalid
└─┬ mocha@1.0.3
  ├── UNMET DEPENDENCY growl 1.5.x
  └── UNMET DEPENDENCY jade 0.20.3

npm ERR! invalid: commander@1.0.1 /home/roman/wc/MINE/webspecter-upstream/node_modules/commander
npm ERR! invalid: diff@1.0.3 /home/roman/wc/MINE/webspecter-upstream/node_modules/diff
npm ERR! missing: growl@1.5.x, required by mocha@1.0.3
npm ERR! missing: jade@0.20.3, required by mocha@1.0.3
npm ERR! not ok code 0
roman@wrench wc/MINE/webspecter-upstream master 0 1083 1 > 
```

test run:

```
roman@wrench wc/MINE/webspecter-upstream master 0 1081 0 > make test             
npm WARN package.json webspecter-test@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/ejs
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/cookie
npm http GET https://registry.npmjs.org/buffer-crc32
npm http GET https://registry.npmjs.org/fresh
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/send
npm http GET https://registry.npmjs.org/cookie-signature
npm http GET https://registry.npmjs.org/merge-descriptors
npm http GET https://registry.npmjs.org/utils-merge
npm http GET https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/path-to-regexp
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/cookie
npm http 304 https://registry.npmjs.org/buffer-crc32
npm http 304 https://registry.npmjs.org/fresh
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/cookie-signature
npm http 200 https://registry.npmjs.org/send
npm http 304 https://registry.npmjs.org/merge-descriptors
npm http 304 https://registry.npmjs.org/escape-html
npm http 304 https://registry.npmjs.org/utils-merge
npm http GET https://registry.npmjs.org/send/-/send-0.3.0.tgz
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/path-to-regexp
npm http 304 https://registry.npmjs.org/serve-static
npm http 200 https://registry.npmjs.org/send/-/send-0.3.0.tgz
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/negotiator
npm http GET https://registry.npmjs.org/ipaddr.js
npm http 304 https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/ipaddr.js
npm http 200 https://registry.npmjs.org/mime
npm http 200 https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
ejs@1.0.0 node_modules/ejs

express@4.3.1 node_modules/express
├── parseurl@1.0.1
├── merge-descriptors@0.0.2
├── utils-merge@1.0.0
├── cookie@0.1.2
├── escape-html@1.0.1
├── debug@0.8.1
├── cookie-signature@1.0.3
├── range-parser@1.0.0
├── fresh@0.2.2
├── qs@0.6.6
├── methods@1.0.0
├── buffer-crc32@0.2.1
├── serve-static@1.1.0
├── path-to-regexp@0.1.2
├── proxy-addr@1.0.0 (ipaddr.js@0.1.2)
├── type-is@1.2.0 (mime@1.2.11)
├── send@0.3.0 (debug@0.8.0, mime@1.2.11)
└── accepts@1.0.1 (negotiator@0.4.3, mime@1.2.11)

/home/roman/wc/MINE/webspecter-upstream/support/server/app.js:2
var app = express.createServer();
                  ^
TypeError: Object function createApplication() {
  var app = function(req, res, next) {
    app.handle(req, res, next);
  };

  mixin(app, proto);
  mixin(app, EventEmitter.prototype);

  app.request = { __proto__: req, app: app };
  app.response = { __proto__: res, app: app };
  app.init();
  return app;
} has no method 'createServer'
    at Object.<anonymous> (/home/roman/wc/MINE/webspecter-upstream/support/server/app.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3


  Simple JavaScript test
    ✓ passes correct examples 
    ✓ catches exceptions 
    ✓ works async 

  Browser
    ✓ doesn't set onConsoleMessage if console option is disabled 
    ✓ sets onConsoleMessage if console option is enabled 
    #visit
      ◦ loads the page: TypeError: 'null' is not an object (evaluating 'document.querySelector('title').textContent')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3
      1) loads the page
      ◦ loads the subpage using config's baseUrl: TypeError: 'null' is not an object (evaluating 'document.querySelector('title').textContent')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3
      2) loads the subpage using config's baseUrl
      3) sets the URL
    .url
      4) "before each" hook

  ✖ 4 of 102 tests failed:

  1) Browser #visit loads the page:
     TypeError: 'null' is not an object (evaluating 'title.should')
      at /home/roman/wc/MINE/webspecter-upstream/spec/unit/browser.coffee:55
      at g (/home/roman/wc/MINE/webspecter-upstream/nodify/lib/modules/events.js:154)
      at /home/roman/wc/MINE/webspecter-upstream/nodify/lib/modules/events.js:67
      at /home/roman/wc/MINE/webspecter-upstream/nodify/lib/nodify.js:66
      at /home/roman/wc/MINE/webspecter-upstream/lib/Browser.js:50

  2) Browser #visit loads the subpage using config's baseUrl:
     TypeError: 'null' is not an object (evaluating 'title.should')
      at /home/roman/wc/MINE/webspecter-upstream/spec/unit/browser.coffee:65
      at g (/home/roman/wc/MINE/webspecter-upstream/nodify/lib/modules/events.js:154)
      at /home/roman/wc/MINE/webspecter-upstream/nodify/lib/modules/events.js:67
      at /home/roman/wc/MINE/webspecter-upstream/nodify/lib/nodify.js:66
      at /home/roman/wc/MINE/webspecter-upstream/lib/Browser.js:50

  3) Browser #visit sets the URL:
     expected 'about:blank' to equal 'http://localhost:4567/'
      at /home/roman/wc/MINE/webspecter-upstream/node_modules/chai/lib/assertion.js:93
      at /home/roman/wc/MINE/webspecter-upstream/node_modules/chai/lib/assertion.js:545
      at /home/roman/wc/MINE/webspecter-upstream/spec/unit/browser.coffee:72
      at g (/home/roman/wc/MINE/webspecter-upstream/nodify/lib/modules/events.js:154)
      at /home/roman/wc/MINE/webspecter-upstream/nodify/lib/modules/events.js:67
      at /home/roman/wc/MINE/webspecter-upstream/nodify/lib/nodify.js:66
      at /home/roman/wc/MINE/webspecter-upstream/lib/Browser.js:50

  4) Browser .url "before each" hook:
     Error: No element found for { xpath: '//a[text()="subpage"]' } in
<html><head></head><body></body></html>
      at /home/roman/wc/MINE/webspecter-upstream/lib/PageQuery.js:266


support/run_tests.sh: line 7: kill: (20367) - No such process
Makefile:2: recipe for target 'test' failed
make: *** [test] Error 1
roman@wrench wc/MINE/webspecter-upstream master 0 1082 2 > 

```

**Comment by jgonera** [comment]
Closing the issue before archiving the repo.
